// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArJ456g2DVwdk97sq2iqxjgZIqTvdXhVM',
    appId: '1:971174406397:web:f47e32672377ca25327694',
    messagingSenderId: '971174406397',
    projectId: 'chat-app-b5d4f',
    authDomain: 'chat-app-b5d4f.firebaseapp.com',
    storageBucket: 'chat-app-b5d4f.appspot.com',
    measurementId: 'G-0B9QTY979F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfBL6xAeRpGiXm6tdT3zMFgzLzYJlHetY',
    appId: '1:971174406397:android:121e9e9d8fc36fa5327694',
    messagingSenderId: '971174406397',
    projectId: 'chat-app-b5d4f',
    storageBucket: 'chat-app-b5d4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoDCAjDjQKUlvWZOQffQTEJpC6Pcng7Dk',
    appId: '1:971174406397:ios:574805edc43c5b16327694',
    messagingSenderId: '971174406397',
    projectId: 'chat-app-b5d4f',
    storageBucket: 'chat-app-b5d4f.appspot.com',
    iosClientId: '971174406397-nc5akd5kgf84dd8isautvmbup00ksh6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
